name: TestBinder
channels:
 - anaconda
 - bioconda
 - conda-forge
dependencies:
 - pandas
 - biopython 
 - seaborn
 - matplotlib
 - pysamstats
 - pysam
 - pyvcf
 - palettable
 - xlwt
 - openpyxl
 - numpy
